In [1]:
import pandas as pd

In [2]:
X_train = pd.read_csv('IMDb_train.csv')
X_test = pd.read_csv('IMDb_test.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')
train_sets = [X_train, X_test]

In [3]:
print(X_train.shape[0], 'Rijen')
print(X_train.shape[1], 'Kolommen')
X_train.head()

404 Rijen
13 Kolommen

,label,collections,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating,url
0,Soldiers_of_the_Empire_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,PT47M,TV-PG,https://www.imdb.com/title/tt0708603
1,Cold_Fire_st_v.txt,Collection: tvseries: Star Trek: Voyager,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,PT46M,TV-PG,https://www.imdb.com/title/tt0708866
2,Armageddon_Game_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,PT46M,TV-PG,https://www.imdb.com/title/tt0708500
3,All_Good_Things_st_ng.txt,Collection: tvseries: Star Trek: The Next Gene...,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,PT1H45M,TV-PG,https://www.imdb.com/title/tt0111281
4,A_Hundred_Yards_Over_the_Rim_tz.txt,Collection: tvseries: The Twilight Zone (1959),"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,PT25M,TV-PG,https://www.imdb.com/title/tt0734541/

In [4]:
print(y_train.shape[0], 'Rijen')
print(y_train.shape[1], 'Kolommen')
y_train.head()

404 Rijen
10 Kolommen

,alien point of view,belonging,father and son,friendship,human vs. captivity,husband and wife,infatuation,obsession,romantic love,time travel
0,1,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,1,0
3,1,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1

In [5]:
columns = ['url', 'collections', 'label']
for i in range(len(train_sets)):
    existing_columns = set(train_sets[i].columns).intersection(columns)
    if existing_columns:
        train_sets[i] = train_sets[i].drop(axis=0, columns=existing_columns)

In [6]:
def rating(text):
    if text == 'TV-PG':
        return 0
    else:
        return 1

for train_set in train_sets:   
    train_set['content rating'] = train_set['content rating'].apply(rating)

In [7]:
counts = train_sets[0]['content rating'].value_counts()
print(counts)

# TV-PG = 0
# TV-14 = 1

train_sets[0].head()

content rating
0    347
1     57
Name: count, dtype: int64

,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,PT47M,0
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,PT46M,0
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,PT46M,0
3,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,PT1H45M,0
4,"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,PT25M,0

In [8]:
types = train_sets[0]['duration'].value_counts()
print(types)

duration
PT46M      127
PT45M       73
PT25M       48
PT43M       37
PT23M       36
PT22M       21
PT50M       20
PT51M       19
PT44M        9
PT1H         3
PT47M        3
PT24M        2
PT1H45M      1
PT26M        1
PT1H32M      1
PT1H3M       1
PT1H27M      1
Name: count, dtype: int64

In [9]:
def count_minutes(text):
    count = 0
    text = str(text)
    for i in range(len(text)):
        if i < 2:
            continue
        if text[i] == 'H' and text[i-2].isdigit():
            count += int(text[i-2:i]) * 60
        elif text[i] == 'H' and text[i-1].isdigit():
            count += int(text[i-1:i]) * 60
        elif text[i] == 'M' and text[i-2].isdigit():
            count += int(text[i-2:i])
        elif text[i] == 'M' and text[i-1].isdigit():
            count += int(text[i-1:i])
    return count
            

for train_set in train_sets:
    train_set['duration'] = train_set['duration'].apply(count_minutes)

In [10]:
train_sets[0].head()

,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,47,0
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,46,0
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,46,0
3,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,105,0
4,"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,25,0

In [11]:
max_rating = train_sets[0]['IMDb rating'].max()

def normalize_score(score):
    return score / max_rating

In [12]:
for train_set in train_sets:
    train_set['IMDb rating'] = train_set['IMDb rating'].apply(normalize_score)

In [13]:
train_sets[0].head(10)

,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",0.800000,Dax and Worf accompany Martok on his first com...,1997-04-28,47,0
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",0.736842,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,46,0
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",0.778947,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,46,0
3,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",0.957895,Capt. Picard finds himself shifting continuall...,1994-05-23,105,0
4,"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",0.852632,The leader of a wagon train across the New Mex...,1961-04-07,25,0
5,"""Star Trek: Deep Space Nine"" Blood Oath (TV Ep...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",0.821053,Three legendary Klingons come to DS9 to see if...,1996-06-01,46,0
6,"""Star Trek: The Next Generation"" Preemptive St...","['Action', 'Adventure', 'Drama']",['Patrick Stewart'],"['Gene Roddenberry', 'René Echevarria', 'Naren...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",0.831579,Following her return from Advanced Tactical Tr...,1994-05-14,45,0
7,"""Star Trek"" The Squire of Gothos (TV Episode 1...","['Action', 'Adventure', 'Sci-Fi']",['Don McDougall'],"['Paul Schneider', 'Gene Roddenberry']","['William Shatner', 'Leonard Nimoy', 'William ...",0.757895,A being that controls matter and creates plane...,1967-01-12,50,0
8,"""Star Trek: Deep Space Nine"" Shattered Mirror ...","['Action', 'Adventure', 'Drama']",['James L. Conway'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",0.747368,When the Mirror Universe counterpart of Sisko&...,1996-04-22,46,0
9,"""Star Trek"" The City on the Edge of Forever (T...","['Action', 'Adventure', 'Sci-Fi']",['Joseph Pevney'],"['Harlan Ellison', 'Gene Roddenberry']","['William Shatner', 'Leonard Nimoy', 'Joan Col...",0.968421,When a temporarily insane Dr. McCoy accidental...,1967-04-06,50,0

In [14]:
bool_columns = ['genre', 'director', 'stars', 'writer']

for column in bool_columns:
    train_sets[0][column] = train_sets[0][column].str.replace('[', '', regex=False).str.replace(']', '', regex=False).str.replace("'", '', regex=False)
    train_sets[0][column] = train_sets[0][column].apply(lambda x: [item.strip() for item in x.split(',')])

    new_columns = {}

    for i, row in train_sets[0].iterrows():
        for item in row[column]:
            new_column = item.strip()
            if new_column not in new_columns:
                new_columns[new_column] = [0] * len(train_sets[0])
            new_columns[new_column][i] = 1

    train_sets[0] = pd.concat([train_sets[0], pd.DataFrame(new_columns)], axis=1)

    train_sets[0] = train_sets[0].drop(columns=[column], axis=1)

In [15]:
train_sets[0].head()

,title,IMDb rating,IMDb description,air date,duration,content rating,Action,Adventure,Drama,Fantasy,...,Michael Michaelian,Bruce D. Arthurs,Michael Rowe,Oceo Ritch,Norman Spinrad,Frank Abatemarco,George F. Slavin,Stanley Adams,Robert Bloch,John Whelpley
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...",0.800000,Dax and Worf accompany Martok on his first com...,1997-04-28,47,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...",0.736842,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,46,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...",0.778947,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,46,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,"""Star Trek: The Next Generation"" All Good Thin...",0.957895,Capt. Picard finds himself shifting continuall...,1994-05-23,105,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,"""The Twilight Zone"" A Hundred Yards Over the R...",0.852632,The leader of a wagon train across the New Mex...,1961-04-07,25,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [17]:
print(train_sets[0].columns)

Index(['title', 'IMDb rating', 'IMDb description', 'air date', 'duration',
       'content rating', 'Action', 'Adventure', 'Drama', 'Fantasy',
       ...
       'Michael Michaelian', 'Bruce D. Arthurs', 'Michael Rowe', 'Oceo Ritch',
       'Norman Spinrad', 'Frank Abatemarco', 'George F. Slavin',
       'Stanley Adams', 'Robert Bloch', 'John Whelpley'],
      dtype='object', length=466)

In [18]:
print(train_sets[0][train_sets[0]['Michael Michaelian'] == 1])

                                                 title  IMDb rating  \
368  "Star Trek: The Next Generation" Too Short a S...     0.642105

                                      IMDb description    air date  duration  \
368  The Enterprise transports an elderly Starfleet...  1992-08-30        45

     content rating  Action  Adventure  Drama  Fantasy  ...  \
368               0       1          1      1        0  ...

     Michael Michaelian  Bruce D. Arthurs  Michael Rowe  Oceo Ritch  \
368                   1                 0             0           0

     Norman Spinrad  Frank Abatemarco  George F. Slavin  Stanley Adams  \
368               0                 0                 0              0

     Robert Bloch  John Whelpley
368             0              0

[1 rows x 466 columns]