In [3]:
import pandas as pd

In [56]:
X_train = pd.read_csv('IMDb_train.csv')
X_test = pd.read_csv('IMDb_test.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')
train_sets = [X_train, X_test]

In [57]:
print(X_train.shape[0], 'Rijen')
print(X_train.shape[1], 'Kolommen')
X_train.head()

404 Rijen
13 Kolommen

,label,collections,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating,url
0,Soldiers_of_the_Empire_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,PT47M,TV-PG,https://www.imdb.com/title/tt0708603
1,Cold_Fire_st_v.txt,Collection: tvseries: Star Trek: Voyager,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,PT46M,TV-PG,https://www.imdb.com/title/tt0708866
2,Armageddon_Game_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,PT46M,TV-PG,https://www.imdb.com/title/tt0708500
3,All_Good_Things_st_ng.txt,Collection: tvseries: Star Trek: The Next Gene...,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,PT1H45M,TV-PG,https://www.imdb.com/title/tt0111281
4,A_Hundred_Yards_Over_the_Rim_tz.txt,Collection: tvseries: The Twilight Zone (1959),"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,PT25M,TV-PG,https://www.imdb.com/title/tt0734541/

In [58]:
print(y_train.shape[0], 'Rijen')
print(y_train.shape[1], 'Kolommen')
y_train.head()

404 Rijen
10 Kolommen

,alien point of view,belonging,father and son,friendship,human vs. captivity,husband and wife,infatuation,obsession,romantic love,time travel
0,1,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,1,0
3,1,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1

In [59]:
columns = ['url', 'collections', 'label']
for i in range(len(train_sets)):
    existing_columns = set(train_sets[i].columns).intersection(columns)
    if existing_columns:
        train_sets[i] = train_sets[i].drop(axis=0, columns=existing_columns)

In [60]:
def rating(text):
    if text == 'TV-PG':
        return 0
    else:
        return 1

for train_set in train_sets:   
    train_set['content rating'] = train_set['content rating'].apply(rating)

In [61]:
counts = train_sets[0]['content rating'].value_counts()
print(counts)

# TV-PG = 0
# TV-14 = 1

train_sets[0].head()

0    347
1     57
Name: content rating, dtype: int64

,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,PT47M,0
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,PT46M,0
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,PT46M,0
3,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,PT1H45M,0
4,"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,PT25M,0

In [64]:
types = train_sets[0]['duration'].value_counts()
print(types)

PT46M      127
PT45M       73
PT25M       48
PT43M       37
PT23M       36
PT22M       21
PT50M       20
PT51M       19
PT44M        9
PT1H         3
PT47M        3
PT24M        2
PT1H45M      1
PT26M        1
PT1H32M      1
PT1H3M       1
PT1H27M      1
Name: duration, dtype: int64

In [62]:
def count_minutes(text):
    count = 0
    for i in range(len(text)):
        if i < 2:
            continue
        if text[i] == 'H' and text[i-2].isdigit():
            count += int(text[i-2:i]) * 60
        elif text[i] == 'H' and text[i-1].isdigit():
            count += int(text[i-1:i]) * 60
        elif text[i] == 'M' and text[i-2].isdigit():
            count += int(text[i-2:i])
        elif text[i] == 'M' and text[i-1].isdigit():
            count += int(text[i-1:i])
        else:
            return count
    return count
            

for train_set in train_sets:
    train_set['duration'] = train_set['duration'].apply(count_minutes)

TypeError: object of type 'float' has no len()