In [100]:
import pandas as pd

In [101]:
X_train = pd.read_csv('Datasets/base_X_train.csv')
X_test = pd.read_csv('Datasets/base_X_test.csv')
train_sets = [X_train, X_test]

In [102]:
X_train.head()

,title,genre,director,writer,stars,IMDb rating,IMDb description,duration,content rating,year,month
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",0.800000,Dax and Worf accompany Martok on his first com...,0.447619,0,1997,4
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",0.736842,"The Caretaker&apos;s remains resonate, which m...",0.438095,0,1995,11
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",0.778947,"Chief O&apos;Brien, who still doesn&apos;t par...",0.438095,0,1996,4
3,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",0.957895,Capt. Picard finds himself shifting continuall...,1.000000,0,1994,5
4,"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",0.852632,The leader of a wagon train across the New Mex...,0.238095,0,1961,4

In [103]:
clean_columns = ['genre', 'director', 'stars', 'writer']

for i in range(len(train_sets)):   
    for column in clean_columns:
        train_sets[i][column] = train_sets[i][column].astype(str).str.replace('[', '', regex=False).str.replace(']', '', regex=False)
        train_sets[i][column] = train_sets[i][column].apply(lambda x: [item.strip() for item in x.split(',') if item.strip()])

print(train_sets[0]['writer'][0][0])

'Gene Roddenberry'

In [104]:
for i in range(len(train_sets)):
    train_sets[i][['genre 1', 'genre 2', 'genre 3']] = pd.DataFrame(train_sets[i]['genre'].tolist(), index=train_sets[i].index)
    train_sets[i] = train_sets[i].drop(['genre'], axis=1)

In [105]:
max_writers = train_sets[0]['writer'].apply(len).max()
print(max_writers)

3

In [106]:
for i in range(len(train_sets)):
    train_sets[i]['writer'] = train_sets[i]['writer'].apply(lambda x: x + [None] * (3 - len(x)) if len(x) < 3 else x)

    train_sets[i][['writer 1', 'writer 2', 'writer 3']] = pd.DataFrame(train_sets[i]['writer'].tolist(), index=train_sets[i].index)

    train_sets[i][['writer 1', 'writer 2', 'writer 3']] = train_sets[i][['writer 1', 'writer 2', 'writer 3']].fillna('None')

    train_sets[i] = train_sets[i].drop(['writer'], axis=1)

In [107]:
train_sets[0].head(10)

,title,director,stars,IMDb rating,IMDb description,duration,content rating,year,month,genre 1,genre 2,genre 3,writer 1,writer 2,writer 3
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...",['LeVar Burton'],"['Avery Brooks', 'Rene Auberjonois', 'Michael ...",0.800000,Dax and Worf accompany Martok on his first com...,0.447619,0,1997,4,'Action','Adventure','Drama','Gene Roddenberry','Rick Berman','Michael Piller'
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...",['Cliff Bole'],"['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",0.736842,"The Caretaker&apos;s remains resonate, which m...",0.438095,0,1995,11,'Action','Adventure','Drama','Gene Roddenberry','Rick Berman','Michael Piller'
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...",['Winrich Kolbe'],"['Avery Brooks', 'Rene Auberjonois', 'Alexande...",0.778947,"Chief O&apos;Brien, who still doesn&apos;t par...",0.438095,0,1996,4,'Action','Adventure','Drama','Gene Roddenberry','Rick Berman','Michael Piller'
3,"""Star Trek: The Next Generation"" All Good Thin...",['Winrich Kolbe'],"['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",0.957895,Capt. Picard finds himself shifting continuall...,1.000000,0,1994,5,'Action','Adventure','Drama','Gene Roddenberry','Ronald D. Moore','Brannon Braga'
4,"""The Twilight Zone"" A Hundred Yards Over the R...",['Buzz Kulik'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",0.852632,The leader of a wagon train across the New Mex...,0.238095,0,1961,4,'Drama','Fantasy','Horror','Rod Serling',None,None
5,"""Star Trek: Deep Space Nine"" Blood Oath (TV Ep...",['Winrich Kolbe'],"['Avery Brooks', 'Rene Auberjonois', 'Alexande...",0.821053,Three legendary Klingons come to DS9 to see if...,0.438095,0,1996,6,'Action','Adventure','Drama','Gene Roddenberry','Rick Berman','Michael Piller'
6,"""Star Trek: The Next Generation"" Preemptive St...",['Patrick Stewart'],"['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",0.831579,Following her return from Advanced Tactical Tr...,0.428571,0,1994,5,'Action','Adventure','Drama','Gene Roddenberry','René Echevarria','Naren Shankar'
7,"""Star Trek"" The Squire of Gothos (TV Episode 1...",['Don McDougall'],"['William Shatner', 'Leonard Nimoy', 'William ...",0.757895,A being that controls matter and creates plane...,0.476190,0,1967,1,'Action','Adventure','Sci-Fi','Paul Schneider','Gene Roddenberry',None
8,"""Star Trek: Deep Space Nine"" Shattered Mirror ...",['James L. Conway'],"['Avery Brooks', 'Rene Auberjonois', 'Michael ...",0.747368,When the Mirror Universe counterpart of Sisko&...,0.438095,0,1996,4,'Action','Adventure','Drama','Gene Roddenberry','Rick Berman','Michael Piller'
9,"""Star Trek"" The City on the Edge of Forever (T...",['Joseph Pevney'],"['William Shatner', 'Leonard Nimoy', 'Joan Col...",0.968421,When a temporarily insane Dr. McCoy accidental...,0.476190,0,1967,4,'Action','Adventure','Sci-Fi','Harlan Ellison','Gene Roddenberry',None

In [108]:
max_director = train_sets[0]['director'].apply(len).min()
print(max_director)

0

In [109]:
for i in range(len(train_sets)):
    train_sets[i][['star 1', 'star 2', 'star 3']] = pd.DataFrame(train_sets[i]['stars'].tolist(), index=train_sets[i].index)
    train_sets[i] = train_sets[i].drop(['stars'], axis=1)

In [110]:
for i in range(len(train_sets)):
    train_sets[i]['director'] = train_sets[i]['director'].apply(lambda x: x + [None] * (3 - len(x)) if len(x) < 3 else x)

    train_sets[i][['director 1', 'director 2', 'director 3']] = pd.DataFrame(train_sets[i]['director'].tolist(), index=train_sets[i].index)

    train_sets[i][['director 1', 'director 2', 'director 3']] = train_sets[i][['director 1', 'director 2', 'director 3']].fillna('None')

    train_sets[i] = train_sets[i].drop(['director'], axis=1)

In [111]:
from sklearn.preprocessing import LabelEncoder

In [112]:
label_encoder = LabelEncoder()

encode_columns = ['genre 1', 'genre 2', 'genre 3', 'writer 1', 'writer 2', 'writer 3', 'star 1', 'star 2', 'star 3', 'director 1', 'director 2', 'director 3']

for column in encode_columns:
    for i in range(len(train_sets)):
        train_sets[i][column] = label_encoder.fit_transform(train_sets[i][column])

In [113]:
train_sets[0].head()

,title,IMDb rating,IMDb description,duration,content rating,year,month,genre 1,genre 2,genre 3,writer 1,writer 2,writer 3,star 1,star 2,star 3,director 1,director 2,director 3
0,"""Star Trek: Deep Space Nine"" Soldiers of the E...",0.800000,Dax and Worf accompany Martok on his first com...,0.447619,0,1997,4,0,1,2,5,65,40,1,47,46,72,11,3
1,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...",0.736842,"The Caretaker&apos;s remains resonate, which m...",0.438095,0,1995,11,0,1,2,5,65,40,30,48,61,19,11,3
2,"""Star Trek: Deep Space Nine"" Armageddon Game (...",0.778947,"Chief O&apos;Brien, who still doesn&apos;t par...",0.438095,0,1996,4,0,1,2,5,65,40,1,47,1,129,11,3
3,"""Star Trek: The Next Generation"" All Good Thin...",0.957895,Capt. Picard finds himself shifting continuall...,1.000000,0,1994,5,0,1,2,5,70,4,40,29,40,129,11,3
4,"""The Twilight Zone"" A Hundred Yards Over the R...",0.852632,The leader of a wagon train across the New Mex...,0.238095,0,1961,4,2,2,3,18,82,66,6,26,17,15,11,3

In [114]:
print(len(train_sets[0].columns))

19

# Vectorization

In [115]:
""" train_sets[0]['description_type'] = train_sets[0]['IMDb description'].apply(type)
train_sets[0]['title_type'] = train_sets[0]['title'].apply(type)
print(train_sets[0]['description_type'].unique())
print(train_sets[0]['title_type'].unique()) """

" train_sets[0]['description_type'] = train_sets[0]['IMDb description'].apply(type)\ntrain_sets[0]['title_type'] = train_sets[0]['title'].apply(type)\nprint(train_sets[0]['description_type'].unique())\nprint(train_sets[0]['title_type'].unique()) "

In [116]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [117]:
stop_words = set(stopwords.words('english'))
contraction_mapping = {
    "wasn't": "was not",
    "didn't": "did not",
    "he's":"he is",
    "doesn't": "does not",
    "hadn't": "had not",
    "hasn't": "has not",
    "won't": "will not",
    "don't": "Do not",
    "it's": "it is",
    "isn't": "is not",
    "can't": "cannot",
    "that's": "that is",
    "i'm": "I am",
    "i'll": "I will",
    "it'll": "it will",
    "couldn't": "could not",
    "they'll": "they will",
    "you'll": "you will",
    "wouldn't": "would not",
    "i've": "I have",
    "that's": "that is",
    "Ma'am": "madam",
    "you're": "you are",
    "she'll": "she will",
    "there's": "there is",
    "don't": "do not",
    "don't": "do not",
    "shan't": "shall not",
    "one's": "ones",
    "she's": "she is",
    "let's": "let us",
    "you'd": "you would",
    "meanwhile, back o...":"",
    "&apos;":"'",
    "apos":"",
    "capt.":"captain",
    "capt" : "captain",
    "&quot;good vs.":"",
    "valentine's Day":"Valentine's_Day",
    "&quot;":"'",
    " ar...":"",
    "throug...":"through.",
    "unite...":"United States.",
    " however, the Robot Dev...":"", 
    "tota...":"totally.",
    "dime...":"dimension.",
    "transporter cy...":"transporter.",
    "reme...":"remembers.",
    "begi...":"begins.",
}

def expand_contractions_in_series(series, contraction_mapping):
    """
    Expand contractions in a Pandas Series.
    """
    def expand_contractions(text):
        for word in word_tokenize(text):
            if word.lower() in contraction_mapping.keys(): 
                text = text.replace(word, contraction_mapping[word.lower()])                    
        return text                 
    
    return series.apply(expand_contractions)

def clean_description(description):
    """
    Tokenizes, lowercases, removes non-alphanumeric tokens, and excludes stopwords.
    """
    if not isinstance(description, str):  
        description = ""
    return ' '.join([word.lower() for word in word_tokenize(description) if word.isalnum() and word.lower() not in stop_words])

In [118]:
text_columns = ['title', 'IMDb description']

for column in text_columns:
    for i in range(len(train_sets)):
        train_sets[i][column] = expand_contractions_in_series(train_sets[i][column], contraction_mapping)
        train_sets[i][column] = train_sets[i][column].apply(clean_description)

In [119]:
train_sets[0].head()

,title,IMDb rating,IMDb description,duration,content rating,year,month,genre 1,genre 2,genre 3,writer 1,writer 2,writer 3,star 1,star 2,star 3,director 1,director 2,director 3
0,star trek deep space nine soldiers empire tv e...,0.800000,dax worf accompany martok first command since ...,0.447619,0,1997,4,0,1,2,5,65,40,1,47,46,72,11,3
1,star trek voyager cold fire tv episode 1995 imdb,0.736842,caretaker remains resonate might well mean mat...,0.438095,0,1995,11,0,1,2,5,65,40,30,48,61,19,11,3
2,star trek deep space nine armageddon game tv e...,0.778947,chief brien still particularly like doctor bas...,0.438095,0,1996,4,0,1,2,5,65,40,1,47,1,129,11,3
3,star trek next generation good things tv episo...,0.957895,captain picard finds shifting continually past...,1.000000,0,1994,5,0,1,2,5,70,4,40,29,40,129,11,3
4,twilight zone hundred yards rim tv episode 196...,0.852632,leader wagon train across new mexico territory...,0.238095,0,1961,4,2,2,3,18,82,66,6,26,17,15,11,3

In [120]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [121]:
max_description = train_sets[0]['IMDb description'].apply(lambda x: len(str(x).split())).max()
print(max_description)
max_title = train_sets[0]['title'].apply(lambda x: len(str(x).split())).max()
print(max_title)

28
13

In [122]:
tfidf = TfidfVectorizer(max_features=100)

text_columns = ['title', 'IMDb description']

for column in text_columns:
    for i in range(len(train_sets)):
        results = tfidf.fit_transform(train_sets[i][column]).toarray()
        tfidf_df = pd.DataFrame(results, columns=[f'{column}_tfidf_{j+1}' for j in range(results.shape[1])])
        train_sets[i] = pd.concat([train_sets[i], tfidf_df], axis=1)
        train_sets[i] = train_sets[i].drop(column, axis=1)

In [123]:
train_sets[0].head()

,IMDb rating,duration,content rating,year,month,genre 1,genre 2,genre 3,writer 1,writer 2,...,IMDb description_tfidf_91,IMDb description_tfidf_92,IMDb description_tfidf_93,IMDb description_tfidf_94,IMDb description_tfidf_95,IMDb description_tfidf_96,IMDb description_tfidf_97,IMDb description_tfidf_98,IMDb description_tfidf_99,IMDb description_tfidf_100
0,0.800000,0.447619,0,1997,4,0,1,2,5,65,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.410992,0.0,0.0,0.0
1,0.736842,0.438095,0,1995,11,0,1,2,5,65,...,0.0,0.0,0.0,0.604963,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.778947,0.438095,0,1996,4,0,1,2,5,65,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3,0.957895,1.000000,0,1994,5,0,1,2,5,70,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.852632,0.238095,0,1961,4,2,2,3,18,82,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0

In [124]:
train_sets[1].head()

,IMDb rating,duration,content rating,year,month,genre 1,genre 2,genre 3,writer 1,writer 2,...,IMDb description_tfidf_91,IMDb description_tfidf_92,IMDb description_tfidf_93,IMDb description_tfidf_94,IMDb description_tfidf_95,IMDb description_tfidf_96,IMDb description_tfidf_97,IMDb description_tfidf_98,IMDb description_tfidf_99,IMDb description_tfidf_100
0,0.789474,0.219048,1,2000,11,1,0,0,5,4,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.852632,0.438095,0,1991,1,0,0,1,3,8,...,0.0,0.0,0.489007,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.831579,0.419048,0,2000,10,0,0,1,3,18,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.810526,0.438095,0,1997,2,0,0,1,3,18,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.778947,0.428571,0,1992,10,0,0,1,3,17,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [125]:
train_sets[0].to_csv('Datasets/alternative_X_train.csv', index=False)
train_sets[1].to_csv('Datasets/alternative_X_test.csv', index=False)